# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 18:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_bot', '0001_initial'),
        ('login_registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_bot.Course')),
                ('user_add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_registration.User')),
            ],
        ),
    ]
